# Generated by Django 2.1.7 on 2020-02-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='Your name', max_length=100)),
                ('your_email', models.EmailField(default='Your email', max_length=100)),
                ('your_number', models.IntegerField(default='Your number', max_length=10)),
            ],
        ),
    ]
