# Generated by Django 2.1.7 on 2020-02-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200211_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='your_mail',
            new_name='mail',
        ),
    ]
