# Generated by Django 2.1.7 on 2020-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200211_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mail',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
