# Generated by Django 2.1.7 on 2020-02-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200216_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
